lesson9
kim563/Python pull request #13
Opened 2024-08-06 16:00 UTC by kim563

2024-08-07 08:24 UTC, kristina71 requested changes

2024-08-07 08:24 UTC, kristina71 commented on lesson9/test_db_employee.py
> +        "isActive": True
вот эти данные все лучше генерировать с помощью билиотеки faker о всех тестах

2024-08-07 08:24 UTC, kristina71 commented on lesson9/test_db_employee.py
> +company_id = 14734
так делать плохо - так как у меня другой ид компании и тесты падают все

2024-08-07 08:24 UTC, kristina71 commented on lesson9/test_db_employee.py
> +        "isActive": True
аналогично предыдущему пункту

2024-08-07 08:24 UTC, kristina71 commented on lesson9/test_db_employee.py
> +        "isActive": True
и тут

2024-08-07 08:24 UTC, kristina71 commented on lesson9/test_db_employee.py
> +        "isActive": True
это тоже неплохо было бы генерировать с помощью библиотеки faker

2024-08-07 08:24 UTC, kristina71 commented on lesson9/db_employee.py
> +                "company_id": company_id
кажется тут не все параметры как будто(но возможно я ошибаюсь(

2024-08-07 08:24 UTC, kristina71 commented on lesson9/db_employee.py
> +class Data_Base:
лучше без подчеркивания

2024-08-07 08:26 UTC, kristina71 commented on lesson9/test_db_employee.py
> +    max_id = db.get_max_id_employee()
он всегда возьмет один и тот же ид (10) так как ты его передаешь + так как ты данные не генерируешь разными - то все записи в базе будут одинаковыми и будет разная выборка каждый раз из бд - соотвественно из-за этого разный результат у теста

пофиксится если будешь генерировать разные данные (и без привязки к конкретному ид)

2024-08-08 13:14 UTC, kim563 commented on lesson9/test_db_employee.py
> +    max_id = db.get_max_id_employee()
не совсем понятно про передачу id (10)... в коде выше мы не передаем id сотрудника. id генерируется на стороне БД. мы передаем только 4 параметра:
`
 db.create_employee(
        body["firstName"],
        body["lastName"],
        body["phone"],
        company_id
        )
`
Что значит "без привязки к конкретному ид"   если нет привязки?
про генерацию тестовых данных (faker) понятно исправлю)

2024-08-15 17:33 UTC, closed without merging